import "./index";
import type { HassEntity, HomeAssistant } from "./types/home-assistant";
import type {
  CoversCardConfig,
  NavbarCardConfig,
  PcCardConfig,
  ProxmoxCardConfig,
  RoomCardConfig,
  UnraidCardConfig,
} from "./types/config";

class MockHaCard extends HTMLElement {}
class MockHaIcon extends HTMLElement {
  static observedAttributes = ["icon"];
  connectedCallback(): void { this.icon = this.getAttribute("icon") || ""; }
  attributeChangedCallback(_name: string, _old: string | null, value: string): void { this.icon = value; }
  set icon(value: string) {
    const symbol = value.includes("light") ? "●" : value.includes("server") ? "▤" : value.includes("monitor") ? "▣" : "◇";
    this.textContent = symbol;
    this.style.display = "inline-grid";
    this.style.placeItems = "center";
  }
}
if (!customElements.get("ha-card")) customElements.define("ha-card", MockHaCard);
if (!customElements.get("ha-icon")) customElements.define("ha-icon", MockHaIcon);

const e = (entity_id: string, state: string, attributes: Record<string, unknown> = {}): HassEntity => ({
  entity_id,
  state,
  attributes: { friendly_name: entity_id.split(".")[1].replaceAll("_", " "), ...attributes },
});

const states = [
  e("sensor.salon_temperature", "21.5", { unit_of_measurement: "°C" }),
  e("sensor.salon_humidity", "46", { unit_of_measurement: "%" }),
  e("climate.salon", "heat", { friendly_name: "Climat Salon", temperature: 20.5, current_temperature: 21.5, target_temp_step: 0.5, min_temp: 7, max_temp: 28 }),
  e("media_player.salon", "playing", { friendly_name: "Musique Salon", media_title: "Jazz du soir", media_artist: "Maison", volume_level: 0.34 }),
  e("media_player.tv_salon", "on", { friendly_name: "Télévision Salon", media_title: "France 2", volume_level: 0.22 }),
  e("light.plafonnier", "on", { friendly_name: "Plafonnier", brightness: 178 }),
  e("light.lampadaire", "on", { friendly_name: "Lampadaire", brightness: 102 }),
  e("light.bibliotheque", "on", { friendly_name: "Bibliothèque", brightness: 216 }),
  e("light.ambiance_tv", "off", { friendly_name: "Ambiance TV", brightness: 0 }),
  e("cover.baie", "open", { friendly_name: "Baie vitrée", current_position: 75 }),
  e("cover.fenetre", "open", { friendly_name: "Fenêtre", current_position: 35 }),
  e("cover.bureau_fenetre", "closed", { friendly_name: "Fenêtre du bureau" }),
  e("cover.bureau_velux", "open", { friendly_name: "Velux du bureau" }),
  e("cover.chambre_principale", "open", { friendly_name: "Chambre principale" }),
  e("cover.chambre_enfant", "closed", { friendly_name: "Chambre enfant" }),
  e("cover.salle_manger", "open", { friendly_name: "Salle à manger" }),
  e("cover.cuisine", "open", { friendly_name: "Cuisine" }),
  e("binary_sensor.pc_online", "on"),
  e("sensor.pc_session", "Unlocked"),
  e("sensor.pc_user", "rso"),
  e("sensor.pc_last_boot", "2026-10-04T16:22:48+00:00"),
  e("sensor.pc_last_activity", "2026-10-05T16:55:06+00:00"),
  e("sensor.pc_system_state", "ApplicationStarted"),
  e("sensor.pc_cpu", "32", { unit_of_measurement: "%" }),
  e("sensor.pc_cpu_temp", "54", { unit_of_measurement: "°C" }),
  e("sensor.pc_gpu", "18", { unit_of_measurement: "%" }),
  e("sensor.pc_gpu_temp", "0", { unit_of_measurement: "°C" }),
  e("sensor.pc_ram", "46", { unit_of_measurement: "%" }),
  e("sensor.pc_storage", "60", { unit_of_measurement: "%" }),
  e("sensor.pc_storage_label", "1,2 / 2 To"),
  e("sensor.pc_drive_c", "C", { Label: "Windows", UsedSpacePercentage: 63, UsedSpaceMB: 322560, TotalSizeMB: 512000 }),
  e("sensor.pc_drive_d", "D", { Label: "Données", UsedSpacePercentage: 41, UsedSpaceMB: 419840, TotalSizeMB: 1024000 }),
  e("sensor.pc_battery", "100", { unit_of_measurement: "%" }),
  e("sensor.pc_battery_status", "High"),
  e("sensor.pc_powerline", "Online"),
  e("sensor.pc_audio_output", "SteelSeries Sonar - Gaming (SteelSeries Sonar Virtual Audio Device)"),
  e("sensor.pc_audio_output_state", "ACTIVE"),
  e("sensor.pc_audio_output_volume", "100", { unit_of_measurement: "%" }),
  e("sensor.pc_audio_output_muted", "False"),
  e("sensor.pc_audio_input", "SteelSeries Sonar - Microphone (SteelSeries Sonar Virtual Audio Device)"),
  e("sensor.pc_audio_input_state", "ACTIVE"),
  e("sensor.pc_audio_input_volume", "0", { unit_of_measurement: "%" }),
  e("sensor.pc_audio_input_muted", "False"),
  e("sensor.pc_audio_sessions", "6"),
  e("sensor.pc_audio_peak", "0"),
  e("sensor.pc_network_count", "3"),
  e("sensor.pc_network_vpn", "Up", { friendly_name: "OpenVPN TAP-Windows6" }),
  e("sensor.pc_network_ethernet", "Up", { friendly_name: "Ethernet 2" }),
  e("sensor.pc_network_wifi", "Down", { friendly_name: "Wi-Fi" }),
  e("sensor.pc_down", "12,4 Mb/s"),
  e("sensor.pc_up", "1,2 Mb/s"),
  e("binary_sensor.unraid_online", "on"),
  e("sensor.unraid_uptime", "18 jours"),
  e("sensor.unraid_array_usage", "68", { unit_of_measurement: "%" }),
  e("sensor.unraid_array_label", "16,3 / 24 To"),
  e("sensor.unraid_healthy_disks", "6"),
  e("sensor.unraid_total_disks", "6"),
  e("sensor.unraid_parity", "Valide"),
  e("sensor.unraid_parity_age", "il y a 12 j"),
  e("sensor.unraid_parity_errors", "0"),
  e("sensor.unraid_cpu", "18", { unit_of_measurement: "%" }),
  e("sensor.unraid_cpu_temp", "49", { unit_of_measurement: "°C" }),
  e("sensor.unraid_disk_max_temp", "48", { unit_of_measurement: "°C" }),
  e("sensor.unraid_ram", "42", { unit_of_measurement: "%" }),
  e("sensor.unraid_down", "38 Mb/s"),
  e("sensor.unraid_up", "8 Mb/s"),
  e("sensor.unraid_version", "7.3.2"),
  e("sensor.unraid_updates", "5"),
  e("sensor.unraid_notifications", "3"),
  e("sensor.unraid_docker_cpu", "3.7", { unit_of_measurement: "%" }),
  e("sensor.unraid_docker_memory", "9.5", { unit_of_measurement: "%" }),
  e("binary_sensor.unraid_ups_connected", "on"),
  e("sensor.unraid_ups_status", "ONLINE"),
  e("sensor.unraid_ups_battery", "100", { unit_of_measurement: "%" }),
  e("sensor.unraid_ups_load", "25", { unit_of_measurement: "%" }),
  e("sensor.unraid_ups_runtime", "1 heure"),
  e("switch.docker_ha", "on"),
  e("switch.docker_mqtt", "on"),
  e("switch.docker_plex", "off"),
  e("switch.docker_grafana", "off"),
  e("switch.vm_homelab", "on"),
  e("switch.vm_windows", "off"),
  e("sensor.vm_homelab_ip", "192.168.1.42"),
  e("sensor.unraid_disk_1_usage", "78", { unit_of_measurement: "%" }),
  e("sensor.unraid_disk_1_capacity", "6,2 / 8 To"),
  e("sensor.unraid_disk_1_temp", "43", { unit_of_measurement: "°C" }),
  e("binary_sensor.unraid_disk_1_healthy", "on"),
  e("sensor.unraid_disk_2_usage", "63", { unit_of_measurement: "%" }),
  e("sensor.unraid_disk_2_capacity", "5 / 8 To"),
  e("sensor.unraid_disk_2_temp", "41", { unit_of_measurement: "°C" }),
  e("binary_sensor.unraid_disk_2_healthy", "on"),
  e("button.unraid_array_start", "2026-10-05T08:00:00+02:00"),
  e("button.unraid_array_stop", "2026-10-05T08:00:00+02:00"),
  e("button.unraid_restart", "2026-10-05T08:00:00+02:00"),
  e("button.unraid_shutdown", "2026-10-05T08:00:00+02:00"),
  e("button.docker_ha_restart", "2026-10-05T08:00:00+02:00"),
  e("button.docker_mqtt_restart", "2026-10-05T08:00:00+02:00"),
  e("button.vm_homelab_restart", "2026-10-05T08:00:00+02:00"),
  e("button.vm_homelab_pause", "2026-10-05T08:00:00+02:00"),
  e("button.vm_homelab_resume", "2026-10-05T08:00:00+02:00"),
  e("binary_sensor.proxmox_online", "on"),
  e("sensor.proxmox_version", "9.0"),
  e("sensor.proxmox_quorum", "3 / 3"),
  e("sensor.proxmox_usage", "42", { unit_of_measurement: "%" }),
  e("sensor.proxmox_memory", "58", { unit_of_measurement: "%" }),
  e("sensor.proxmox_memory_label", "186 Go"),
  e("sensor.proxmox_storage", "59", { unit_of_measurement: "%" }),
  e("sensor.proxmox_storage_label", "14,2 / 24 To"),
  e("sensor.proxmox_ceph", "HEALTH_OK"),
  e("sensor.proxmox_backup", "2026-10-06T01:30:00+02:00"),
  e("binary_sensor.proxmox_backup_running", "off"),
  e("sensor.proxmox_uptime", "291.2725", { unit_of_measurement: "h" }),
  e("sensor.proxmox_memory_used", "11.3387", { unit_of_measurement: "GiB" }),
  e("sensor.proxmox_memory_total", "15.4001", { unit_of_measurement: "GiB" }),
  e("sensor.proxmox_alerts", "0"),
  e("binary_sensor.pve_01_online", "on"),
  e("binary_sensor.pve_02_online", "on"),
  e("binary_sensor.pve_03_online", "on"),
  e("sensor.pve_01_cpu", "38", { unit_of_measurement: "%" }),
  e("sensor.pve_02_cpu", "47", { unit_of_measurement: "%" }),
  e("sensor.pve_03_cpu", "41", { unit_of_measurement: "%" }),
  e("sensor.pve_01_temp", "48", { unit_of_measurement: "°C" }),
  e("sensor.pve_02_temp", "51", { unit_of_measurement: "°C" }),
  e("sensor.pve_03_temp", "46", { unit_of_measurement: "°C" }),
  e("switch.proxmox_vm_ha", "on"),
  e("switch.proxmox_vm_windows", "off"),
  e("switch.proxmox_lxc_mqtt", "on"),
  e("switch.proxmox_lxc_grafana", "on"),
  e("sensor.proxmox_vm_ha_ip", "192.168.1.50"),
].reduce<Record<string, HassEntity>>((map, item) => ({ ...map, [item.entity_id]: item }), {});

const hass: HomeAssistant = {
  states,
  themes: { darkMode: false },
  formatEntityState: (state) => `${state.state}${state.attributes.unit_of_measurement ? ` ${state.attributes.unit_of_measurement}` : ""}`,
  callService: async (domain, service, data, target) => {
    console.info("Service Home Assistant simulé", { domain, service, data, target });
  },
};

const room: RoomCardConfig = {
  type: "custom:auralis-room-card",
  name: "Salon",
  theme: "carbon",
  card_background: { mode: "gradient", gradient: "linear-gradient(145deg, #09111A 0%, #0D1822 58%, #081018 100%)" },
  show_grid: false,
  background_position: "center",
  accent_color: "#79d6f2",
  temperature_entity: "sensor.salon_temperature",
  humidity_entity: "sensor.salon_humidity",
  climate_entity: "climate.salon",
  media_player_entity: "media_player.salon",
  ambiance: { label: "Ambiance", icon: "mdi:creation-outline", position: "bottom-right" },
  scenes: [
    { entity: "scene.soiree_salon", label: "Mode soirée", icon: "mdi:weather-night" },
    { entity: "scene.normal_salon", label: "Mode normal", icon: "mdi:lightbulb-group-outline" },
  ],
  subtitle: "Aucun appareil en alerte",
  left_controls: [{ type: "lights", label: "Lumières", icon: "mdi:ceiling-light-outline" }],
  right_controls: [
    { type: "media", entity: "media_player.salon", label: "Musique", icon: "mdi:music-note" },
    { type: "tv", entity: "media_player.tv_salon", label: "TV", icon: "mdi:television" },
  ],
  thermostat: {
    entity: "climate.salon",
    position: "bottom-left",
    label: "Thermostat",
    step: 0.5,
    label_color: "#b9c6d5",
    value_color: "#ffffff",
    button_color: "#79d6f2",
    background_color: "rgba(13,18,25,.78)",
    border_color: "rgba(121,214,242,.28)",
  },
  lights: ["light.plafonnier", "light.lampadaire", "light.bibliotheque", "light.ambiance_tv"],
  covers: ["cover.baie", "cover.fenetre"],
};

const covers: CoversCardConfig = {
  type: "custom:auralis-covers-card",
  theme: "carbon",
  groups: [
    { name: "Salon", covers: ["cover.baie", "cover.fenetre"] },
    { name: "Bureau", covers: ["cover.bureau_fenetre", "cover.bureau_velux"] },
    { name: "Chambres", covers: ["cover.chambre_principale", "cover.chambre_enfant"] },
    { name: "Salle à manger", covers: ["cover.salle_manger", "cover.cuisine"] },
  ],
};

const pc: PcCardConfig = {
  type: "custom:auralis-pc-card",
  name: "Aurora",
  theme: "carbon",
  card_background: { mode: "gradient", gradient: "linear-gradient(145deg, #09111A 0%, #0D1822 58%, #081018 100%)" },
  show_grid: false,
  background_image: "/pc-bureau.png",
  background_position: "58% center",
  image_opacity: 35,
  accent_color: "#7997ff",
  online_entity: "binary_sensor.pc_online",
  session_entity: "sensor.pc_session",
  user_entity: "sensor.pc_user",
  last_boot_entity: "sensor.pc_last_boot",
  last_activity_entity: "sensor.pc_last_activity",
  system_state_entity: "sensor.pc_system_state",
  cpu_entity: "sensor.pc_cpu",
  // Capteur CPU volontairement absent et température GPU à 0 : les deux zones sont masquées.
  gpu_entity: "sensor.pc_gpu",
  gpu_temperature_entity: "sensor.pc_gpu_temp",
  memory_entity: "sensor.pc_ram",
  drives: [
    { entity: "sensor.pc_drive_c", label: "Système C:" },
    { entity: "sensor.pc_drive_d", label: "Données D:" },
  ],
  battery_percentage_entity: "sensor.pc_battery",
  battery_status_entity: "sensor.pc_battery_status",
  battery_powerline_entity: "sensor.pc_powerline",
  audio_output_entity: "sensor.pc_audio_output",
  audio_output_state_entity: "sensor.pc_audio_output_state",
  audio_output_volume_entity: "sensor.pc_audio_output_volume",
  audio_output_muted_entity: "sensor.pc_audio_output_muted",
  audio_input_entity: "sensor.pc_audio_input",
  audio_input_state_entity: "sensor.pc_audio_input_state",
  audio_input_volume_entity: "sensor.pc_audio_input_volume",
  audio_input_muted_entity: "sensor.pc_audio_input_muted",
  audio_sessions_entity: "sensor.pc_audio_sessions",
  audio_peak_entity: "sensor.pc_audio_peak",
  network_total_entity: "sensor.pc_network_count",
  network_interfaces: [
    { entity: "sensor.pc_network_vpn", label: "OpenVPN" },
    { entity: "sensor.pc_network_ethernet", label: "Ethernet 2" },
    { entity: "sensor.pc_network_wifi", label: "Wi-Fi" },
  ],
  network_down_entity: "sensor.pc_down",
  network_up_entity: "sensor.pc_up",
  lock_entity: "button.pc_lock",
  sleep_entity: "button.pc_sleep",
  restart_entity: "button.pc_restart",
  shutdown_entity: "button.pc_shutdown",
};

const unraid: UnraidCardConfig = {
  type: "custom:auralis-unraid-card",
  name: "Atlas",
  theme: "carbon",
  card_background: { mode: "gradient", gradient: "linear-gradient(145deg, #09111A 0%, #0D1822 58%, #081018 100%)" },
  show_grid: false,
  background_image: "/nas.png",
  background_position: "51% center",
  accent_color: "#ff8055",
  status_entity: "binary_sensor.unraid_online",
  uptime_entity: "sensor.unraid_uptime",
  array_usage_entity: "sensor.unraid_array_usage",
  array_label_entity: "sensor.unraid_array_label",
  healthy_disks_entity: "sensor.unraid_healthy_disks",
  total_disks_entity: "sensor.unraid_total_disks",
  parity_entity: "sensor.unraid_parity",
  parity_age_entity: "sensor.unraid_parity_age",
  parity_errors_entity: "sensor.unraid_parity_errors",
  cpu_entity: "sensor.unraid_cpu",
  cpu_temperature_entity: "sensor.unraid_cpu_temp",
  disk_temperature_entity: "sensor.unraid_disk_max_temp",
  memory_entity: "sensor.unraid_ram",
  network_down_entity: "sensor.unraid_down",
  network_up_entity: "sensor.unraid_up",
  version_entity: "sensor.unraid_version",
  updates_entity: "sensor.unraid_updates",
  notifications_entity: "sensor.unraid_notifications",
  docker_cpu_entity: "sensor.unraid_docker_cpu",
  docker_memory_entity: "sensor.unraid_docker_memory",
  ups_connected_entity: "binary_sensor.unraid_ups_connected",
  ups_status_entity: "sensor.unraid_ups_status",
  ups_battery_entity: "sensor.unraid_ups_battery",
  ups_load_entity: "sensor.unraid_ups_load",
  ups_runtime_entity: "sensor.unraid_ups_runtime",
  array_start_entity: "button.unraid_array_start",
  array_stop_entity: "button.unraid_array_stop",
  restart_entity: "button.unraid_restart",
  shutdown_entity: "button.unraid_shutdown",
  disks: [
    { name: "Disque 1", group: "Array", show_on_card: true, usage_entity: "sensor.unraid_disk_1_usage", capacity_entity: "sensor.unraid_disk_1_capacity", temperature_entity: "sensor.unraid_disk_1_temp", status_entity: "binary_sensor.unraid_disk_1_healthy" },
    { name: "Disque 2", group: "Array", show_on_card: true, usage_entity: "sensor.unraid_disk_2_usage", capacity_entity: "sensor.unraid_disk_2_capacity", temperature_entity: "sensor.unraid_disk_2_temp", status_entity: "binary_sensor.unraid_disk_2_healthy" },
  ],
  docker_group_labels: { Maison: "Domotique", Médias: "Multimédia", default: "Applications" },
  vm_group_labels: { Production: "Serveurs", Bureau: "Postes de travail", default: "Machines virtuelles" },
  docker: [
    { name: "Home Assistant", entity: "switch.docker_ha", group: "Maison", restart_entity: "button.docker_ha_restart" },
    { name: "Mosquitto", entity: "switch.docker_mqtt", group: "Maison", restart_entity: "button.docker_mqtt_restart" },
    { name: "Plex", entity: "switch.docker_plex", group: "Médias" },
    { name: "Grafana", entity: "switch.docker_grafana", group: "Infrastructure" },
  ],
  vms: [
    { name: "HomeLab Ubuntu", entity: "switch.vm_homelab", group: "Production", vcpus: 4, memory: "8 Go", storage: "120 Go", ip_entity: "sensor.vm_homelab_ip", restart_entity: "button.vm_homelab_restart", pause_entity: "button.vm_homelab_pause", resume_entity: "button.vm_homelab_resume", console_url: "#" },
    { name: "Windows 11", entity: "switch.vm_windows", group: "Bureau", vcpus: 8, memory: "16 Go", storage: "256 Go" },
  ],
};

const navbar: NavbarCardConfig = {
  type: "custom:auralis-navbar-card",
  name: "Navigation principale",
  theme: "carbon",
  items: [
    { label: "Accueil", icon: "mdi:home-outline", path: "/" },
    { label: "Pièces", icon: "mdi:floor-plan", path: "/pieces" },
    { label: "Systèmes", icon: "mdi:server-network", path: "/systemes", badge_entity: "sensor.unraid_notifications" },
    { label: "Énergie", icon: "mdi:lightning-bolt-outline", path: "/energie" },
  ],
};

const proxmox: ProxmoxCardConfig = {
  type: "custom:auralis-proxmox-card",
  name: "Proxmox Jarvis",
  theme: "carbon",
  background_image: "/unraid.png",
  background_position: "47% center",
  accent_color: "#50d59b",
  status_entity: "binary_sensor.proxmox_online",
  version_entity: "sensor.proxmox_version",
  quorum_entity: "sensor.proxmox_quorum",
  cluster_usage_entity: "sensor.proxmox_usage",
  memory_entity: "sensor.proxmox_memory",
  memory_label_entity: "sensor.proxmox_memory_label",
  info_columns: 3,
  info_items: [
    { entity: "sensor.proxmox_uptime", label: "En ligne depuis", icon: "mdi:clock-outline", format: "duration", duration_unit: "hours" },
    { entity: "sensor.proxmox_backup", label: "Sauvegarde", icon: "mdi:backup-restore", format: "datetime", active_entity: "binary_sensor.proxmox_backup_running", active_text: "En cours" },
    { entity: "sensor.proxmox_memory_used", label: "RAM utilisée", icon: "mdi:memory", format: "ratio", total_entity: "sensor.proxmox_memory_total", unit: "Gio", precision: 1 },
  ],
  storage_entity: "sensor.proxmox_storage",
  storage_label_entity: "sensor.proxmox_storage_label",
  storages: [
    { name: "Local système", usage_entity: "sensor.proxmox_storage", capacity_entity: "sensor.proxmox_storage_label" },
    { name: "Volumes des VM", usage_entity: "sensor.proxmox_storage" },
    { name: "Sauvegardes", usage_entity: "sensor.proxmox_storage", show_on_card: false },
  ],
  disks: [{ name: "NVMe physique", capacity_entity: "sensor.proxmox_storage_label" }],
  ceph_entity: "sensor.proxmox_ceph",
  backup_entity: "sensor.proxmox_backup",
  alerts_entity: "sensor.proxmox_alerts",
  backup_action_entity: "button.proxmox_backup_now",
  restart_entity: "button.proxmox_cluster_restart",
  shutdown_entity: "button.proxmox_cluster_shutdown",
  nodes: [
    { name: "pve-01", status_entity: "binary_sensor.pve_01_online", cpu_entity: "sensor.pve_01_cpu", temperature_entity: "sensor.pve_01_temp", restart_entity: "button.pve_01_restart", shutdown_entity: "button.pve_01_shutdown" },
    { name: "pve-02", status_entity: "binary_sensor.pve_02_online", cpu_entity: "sensor.pve_02_cpu", temperature_entity: "sensor.pve_02_temp", restart_entity: "button.pve_02_restart", shutdown_entity: "button.pve_02_shutdown" },
    { name: "pve-03", status_entity: "binary_sensor.pve_03_online", cpu_entity: "sensor.pve_03_cpu", temperature_entity: "sensor.pve_03_temp", restart_entity: "button.pve_03_restart", shutdown_entity: "button.pve_03_shutdown" },
  ],
  vms: [
    { name: "Home Assistant", entity: "switch.proxmox_vm_ha", node: "pve-01", group: "Maison", vcpus: 4, memory: "8 Go", storage: "64 Go", ip_entity: "sensor.proxmox_vm_ha_ip", start_entity: "button.proxmox_vm_ha_start", restart_entity: "button.proxmox_vm_ha_restart", console_url: "#" },
    { name: "Windows 11", entity: "switch.proxmox_vm_windows", node: "pve-02", group: "Bureau", vcpus: 8, memory: "16 Go", storage: "256 Go", start_entity: "button.proxmox_vm_windows_start" },
  ],
  containers: [
    { name: "Mosquitto", entity: "switch.proxmox_lxc_mqtt", node: "pve-01", group: "Maison", vcpus: 1, memory: "1 Go", restart_entity: "button.proxmox_lxc_mqtt_restart" },
    { name: "Grafana", entity: "switch.proxmox_lxc_grafana", node: "pve-03", group: "Infrastructure", vcpus: 2, memory: "2 Go", restart_entity: "button.proxmox_lxc_grafana_restart" },
  ],
};

const mount = <T extends HTMLElement & { hass?: HomeAssistant; setConfig(config: unknown): void }>(tag: string, config: unknown): void => {
  const card = document.createElement(tag) as T;
  card.setConfig(config);
  card.hass = hass;
  document.querySelector("#demo")?.append(card);
};

mount("auralis-navbar-card", navbar);
mount("auralis-room-card", room);
mount("auralis-covers-card", covers);
mount("auralis-pc-card", pc);
mount("auralis-unraid-card", unraid);
mount("auralis-proxmox-card", proxmox);
